/** Lista de hunts Baiak-Idle (nome + level) para seleção na extensão. */
window.BAIAK_IDLE_HUNT_RANKS = [
  { id: 'todas', label: 'Todas', min: 0, max: 9999 },
  { id: '1-19', label: '1–19', min: 1, max: 19 },
  { id: '20-49', label: '20–49', min: 20, max: 49 },
  { id: '50-99', label: '50–99', min: 50, max: 99 },
  { id: '100-149', label: '100–149', min: 100, max: 149 },
  { id: '150-199', label: '150–199', min: 150, max: 199 },
  { id: '200-249', label: '200–249', min: 200, max: 249 },
  { id: '250-299', label: '250–299', min: 250, max: 299 },
  { id: '300+', label: '300+', min: 300, max: 9999 }
];

window.BAIAK_IDLE_HUNTS = [
  { name: 'Troll Cave', level: 1 },
  { name: 'Elf', level: 8 },
  { name: 'Amazon', level: 9 },
  { name: 'Minotaur', level: 10 },
  { name: 'Kongra', level: 10 },
  { name: 'Cyclopolis', level: 15 },
  { name: 'Corym Skirmisher', level: 30 },
  { name: 'Stone Refiner', level: 30 },
  { name: 'Giant Spider', level: 50 },
  { name: 'Crawler', level: 50 },
  { name: 'Glooth Bandit', level: 60 },
  { name: 'Hero', level: 60 },
  { name: 'Cult', level: 80 },
  { name: 'Dragon Lair', level: 80 },
  { name: 'Werebadge', level: 90 },
  { name: 'Hydra', level: 100 },
  { name: 'Behemoth', level: 100 },
  { name: 'Orclops', level: 100 },
  { name: 'Grim Reaper', level: 130 },
  { name: 'Wyrm', level: 130 },
  { name: 'Werehyaena', level: 140 },
  { name: 'Asuras', level: 150 },
  { name: 'Dark Torturer', level: 150 },
  { name: 'Wereliones', level: 170 },
  { name: 'Draken', level: 180 },
  { name: 'Mitmah Seer', level: 180 },
  { name: 'Cobras', level: 190 },
  { name: 'Undead Dragon', level: 200 },
  { name: 'Cliff Strider', level: 200 },
  { name: 'Hideous Fungus', level: 200 },
  { name: 'Magma Crawler', level: 200 },
  { name: 'Dread Intruder', level: 200 },
  { name: 'Falcon', level: 210 },
  { name: 'Vexclaw', level: 210 },
  { name: 'Grimeleech', level: 220 },
  { name: 'Choking Fear', level: 240 },
  { name: "Crazed Elf's", level: 240 },
  { name: 'Guzzlemaw', level: 250 },
  { name: 'Raubritter', level: 250 },
  { name: 'Catacomb', level: 250 },
  { name: 'Prison', level: 250 },
  { name: 'Lion Knight', level: 270 },
  { name: 'Mega Dragon', level: 290 },
  { name: 'Naga Lair', level: 300, lean: 'exp' },
  { name: 'True Azura', level: 300, lean: 'exp' },
  { name: 'Freakish Lost Soul', level: 300, lean: 'exp' },
  { name: 'Bulltaur', level: 350, lean: 'exp' },
  { name: 'Gazer', level: 350, lean: 'loot' },
  { name: 'Bashmu', level: 350, lean: 'loot' },
  { name: 'Inferniarch', level: 450, lean: 'exp' },
  { name: 'girtablilu warrior', level: 460, lean: 'loot' },
  { name: 'Livraria ICE', level: 500, lean: 'loot' },
  { name: 'Livraria FIRE', level: 500, lean: 'exp' },
  { name: 'Livraria EARTH', level: 500, lean: 'exp' },
  { name: 'Livraria ENERGY', level: 500, lean: 'exp' },
  { name: 'Quara Raider', level: 600, lean: 'exp' },
  { name: 'Norcferatu Nightweaver', level: 600, lean: 'exp' },
  { name: 'Lavafungos', level: 610, lean: 'loot' },
  { name: 'Afflicted Strider', level: 610, lean: 'loot' },
  { name: 'Varnished Diremaw', level: 610, lean: 'loot' },
  { name: 'Crypt Construct', level: 700, lean: 'exp' },
  { name: 'Crystal Enigma', level: 800, lean: 'loot' },
  { name: 'Rotten Golem', level: 800, lean: 'loot' },
  { name: 'Cloak Of Terror', level: 800, lean: 'exp' },
  { name: 'Monster Graveyard', level: 800, lean: 'loot' },
  { name: 'Sparkling Pools', level: 800, lean: 'exp' },
  { name: 'Infernal Demon', level: 800, lean: 'loot' },
  { name: 'Bony Sea Devil', level: 800, lean: 'loot' },
  { name: 'Dark Thais', level: 800, lean: 'loot' }
];
